#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=0
while [ $a -le 9 ]
do
	a=$((a + 1))
	if [ $a == 4 ]
	then
		echo "bad luck"
	elif [ $a == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
