#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=0
while [ $a -le 19 ]
do
	a=$((a + 1))
	echo $a
	case $a in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
